import {sistaBrain} from './sista-brain.js';
import {hydrateAssets} from './asset-loader.js';
await hydrateAssets();
const $=s=>document.querySelector(s);
const body=document.body,doors=$('#doors'),onboarding=$('#onboarding'),resources=$('#resources'),speechTitle=$('#speech-title'),speechCopy=$('#speech-copy'),sistaDialog=$('#sista-dialog');
let voice=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,currentMessage={title:'Hi there! I’m Sista Lee.',copy:"I’ll be your librarian, book narrator, crochet teacher, and game coach. I’ll stay with you throughout your visit."};
const storeKey='leola.cozy.member.v1';
function safeGet(){try{return JSON.parse(localStorage.getItem(storeKey)||'null')}catch{return null}}
function safeSet(v){try{localStorage.setItem(storeKey,JSON.stringify(v));return true}catch{return false}}
function setMessage(title,copy,speak=true){currentMessage={title,copy};speechTitle.textContent=title;speechCopy.textContent=copy;if(speak&&voice)talk(`${title} ${copy}`)}
function talk(text){if(!voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.92;const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>v.lang==='en-US'&&/female|Jenny|Aria|Samantha|Zira/i.test(v.name))||vs.find(v=>v.lang==='en-US')||null;speechSynthesis.speak(u)}
function spark(count=24){const host=$('#sparkles');for(let i=0;i<count;i++){const e=document.createElement('i');e.className='spark';e.style.left=(45+Math.random()*18)+'%';e.style.top=(48+Math.random()*18)+'%';e.style.setProperty('--x',(Math.random()*280-140)+'px');e.style.setProperty('--y',(Math.random()*220-160)+'px');host.append(e);setTimeout(()=>e.remove(),1900)}}
function showDesk(){body.dataset.phase='inside';doors.setAttribute('aria-hidden','true');setTimeout(()=>{onboarding.hidden=false;onboarding.querySelector('input')?.focus();setMessage('Welcome to my desk.',"Before we explore, tell me your name and email so I can prepare your library card. I’ll stay with you while you read, watch lessons, and practice in the Game House.")},reduced?10:650)}
async function enter(useVoice){voice=useVoice;$('#voice-toggle').textContent=voice?'Voice preview on':'Voice preview off';$('#voice-toggle').setAttribute('aria-pressed',String(voice));body.dataset.phase='entering';setMessage('Come on in.',"The doors are opening. I’ll be waiting right here at my desk.");if(useVoice&&navigator.mediaDevices?.getUserMedia&&window.isSecureContext){navigator.mediaDevices.getUserMedia({audio:true,video:false}).then(s=>s.getTracks().forEach(t=>t.stop())).catch(()=>{});}setTimeout(showDesk,reduced?20:2850)}
function cardId(){return 'LL-'+Math.random().toString(36).slice(2,6).toUpperCase()+'-'+Date.now().toString(36).slice(-4).toUpperCase()}
function presentCard(member){$('#card-name').textContent=member.name;$('#card-number').textContent=member.card;$('#card-date').textContent=member.issued;$('#card-open').hidden=false;onboarding.hidden=true;spark(38);setMessage(`Here you go, ${member.name}.`,"This is your Leola’s Learning Library card. Take it with you—your reading and game progress can grow from here.");const d=$('#card-dialog');d.showModal();setTimeout(()=>d.querySelector('#accept-card')?.focus(),350)}
$('#enter').addEventListener('click',()=>enter(true));$('#enter-text').addEventListener('click',()=>enter(false));
$('#voice-toggle').addEventListener('click',()=>{voice=!voice;$('#voice-toggle').textContent=voice?'Voice preview on':'Voice preview off';$('#voice-toggle').setAttribute('aria-pressed',String(voice));if(!voice)speechSynthesis?.cancel?.();else talk(`${currentMessage.title} ${currentMessage.copy}`)});
$('#motion-toggle').addEventListener('click',()=>{reduced=!reduced;$('#motion-toggle').textContent=reduced?'Full motion':'Less motion';$('#motion-toggle').setAttribute('aria-pressed',String(reduced))});
$('#repeat').addEventListener('click',()=>talk(`${currentMessage.title} ${currentMessage.copy}`));$('#stop-speech').addEventListener('click',()=>speechSynthesis?.cancel?.());
$('#join-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#member-name').value.trim(),email=$('#member-email').value.trim();if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){$('#join-error').textContent='Enter a name and a valid email address.';return;}$('#join-error').textContent='';const member={name,email,card:cardId(),issued:new Date().toLocaleDateString(),createdAt:new Date().toISOString()};safeSet(member);presentCard(member)});
$('#card-dialog .close').addEventListener('click',()=>$('#card-dialog').close());$('#card-open').addEventListener('click',()=>{const m=safeGet();if(m)presentCard(m)});
$('#accept-card').addEventListener('click',()=>{$('#card-dialog').close();resources.hidden=false;spark(32);setMessage('Your library is open.',"Choose one of our two books, watch a crochet video lesson, or pick one of the five Game House covers and play. Sista Lee is available throughout the library.");resources.scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'})});
const returning=safeGet();if(returning){$('#member-name').value=returning.name||'';$('#member-email').value=returning.email||'';$('#card-open').hidden=false}

sistaBrain.addEventListener('status',e=>{const n=$('#brain-status');if(!n)return;const {status,detail}=e.detail;n.textContent=status==='model-ready'?'Sista Brain 360M is ready on this device.':status==='model-loading'?(detail||'Sista Brain is warming…'):'Instant library knowledge ready.';});
$('#ask-sista').addEventListener('click',()=>{sistaDialog.showModal();$('#sista-question').focus();});
$('#sista-dialog .close').addEventListener('click',()=>sistaDialog.close());
$('#sista-form').addEventListener('submit',async e=>{e.preventDefault();const q=$('#sista-question').value.trim();if(!q)return;const out=$('#sista-answer');out.textContent='Sista Lee is checking the library lesson…';const result=await sistaBrain.answer(q);out.textContent=result.text;out.dataset.mode=result.mode;if(voice)talk(result.text);});
