/* REGION: LEOLA.READER | TAG: PAGEFLIP.PRESERVATION
WHAT: reuse canonical books and their native PageFlip setup; add top-left Leola.
WHO: LeeWay; WHY: keep folding behavior, replace duplicate old guide initialization.
WHERE: reader adapter; WHEN: 2026-09-16; HOW: same-origin view, canonical files unchanged.
LICENSE: MIT. Book text is read verbatim, never rewritten by the language model. */
import {leola} from './leola-presence.js';import {loadState,saveBook} from './learning-state.js';
const books={story:{id:'needle-and-yarn',file:'d6jq33mv39.html',title:'Needle & Yarn'},instruction:{id:'crochet-mastery',file:'0lbzci75tc.html',title:'Crochet Mastery'}};
const params=new URLSearchParams(location.search),book=books[params.get('book')]||books.instruction;const frame=document.querySelector('#book-frame'),status=document.querySelector('#reader-status');let flip=null,auto=false,automaticFlip=false,readId=0;
document.title=book.title+' · Read with Leola';leola.show('reader');
const controls=document.createElement('div');controls.className='leola-reader-controls';controls.innerHTML='<span class="leola-page-label">Preparing book…</span><button data-read="prev">← Previous</button><button data-read="next">Next →</button><button data-read="page">Read this page</button><button data-read="all">Read onward</button><button data-read="stop">Stop reading</button><button data-read="slow">Slower voice</button>';leola.el.append(controls);
function halt(){auto=false;readId++;leola.stop();}
function content(){const p=frame.contentDocument?.querySelectorAll('.page')[flip.getCurrentPageIndex()];if(!p)return '';const main=p.querySelector('.story-page,.instruction-page,.cover-page,.dedication-page')||p;return main.textContent.replace(/\s+/g,' ').trim()||p.querySelector('img')?.alt||'';}
async function read(all=false){if(!flip)return;halt();auto=all;const id=readId;leola.setMuted(false);do{const index=flip.getCurrentPageIndex();const text=content();const ok=await leola.speak(text||'This page is an illustration.');if(!ok||id!==readId||!auto)break;if(index+1>=flip.getPageCount()){auto=false;break;}automaticFlip=true;flip.flip(index+1);await new Promise(r=>setTimeout(r,1100));}while(auto&&id===readId);}
controls.addEventListener('click',e=>{const key=e.target.closest('[data-read]')?.dataset.read;if(!key||!flip)return;if(key==='page')read(false);if(key==='all')read(true);if(key==='stop')halt();if(key==='slow'){leola.rate=.8;status.textContent='Narration speed: slower';}if(key==='next'||key==='prev'){halt();key==='next'?flip.flipNext():flip.flipPrev();}});
leola.el.querySelector('[data-action=stop]').addEventListener('click',halt);document.querySelector('.reader-exit').addEventListener('click',halt);
window.__leolaReaderSpeak=(text,callback)=>leola.speak(text).then(ok=>{if(ok)callback?.();});
function update(){const index=flip.getCurrentPageIndex();controls.querySelector('.leola-page-label').textContent=`${book.title} · ${index+1} / ${flip.getPageCount()}`;const ok=saveBook(book.id,index,flip.getPageCount());status.textContent=ok?'Position saved on this device.':'Position could not be saved: browser storage unavailable.';window.__readerProof={book:book.id,page:index,count:flip.getPageCount(),engine:'original-page-flip',canonicalFileUnchanged:true};}
async function init(){try{const response=await fetch(book.file);if(!response.ok)throw new Error('Book returned '+response.status);const original=await response.text();const doc=new DOMParser().parseFromString(original,'text/html');const base=doc.createElement('base');base.href=new URL('./',location.href).href;doc.head.prepend(base);for(const s of [...doc.querySelectorAll('script')]){const src=s.getAttribute('src')||'';if(/agent-lee-final\.js|book-narration\.js/.test(src)||s.textContent.includes("Agent Lee not found, creating it manually"))s.remove();}const style=doc.createElement('style');style.textContent='#agent-lee-card,.agent-lee-card,.home-button,#speak-btn,#stop-btn,.voice-controls{display:none!important}';doc.head.append(style);const shim=doc.createElement('script');shim.textContent="window.speakText=(text,callback)=>parent.__leolaReaderSpeak(text,callback);window.isAutoReading=false;try{localStorage.setItem('auto-narration','false')}catch{}";doc.head.prepend(shim);frame.addEventListener('load',()=>{try{flip=frame.contentWindow.pageFlip;if(!flip)throw new Error('Original PageFlip did not initialize');flip.on('flip',()=>{if(automaticFlip)automaticFlip=false;else halt();update();});const saved=loadState().books[book.id];const requested=Number(params.get('page'));const target=params.has('page')?requested:saved?.page;if(Number.isInteger(target)&&target>=0&&target<flip.getPageCount())flip.turnToPage(target);update();}catch(e){status.textContent='Reader could not start: '+e.message;}});frame.srcdoc='<!doctype html>'+doc.documentElement.outerHTML;}catch(e){status.textContent='Book unavailable: '+e.message;const link=document.createElement('a');link.href=book.file;link.textContent='Open the original book directly';link.className='reader-exit';link.style.top='60px';document.body.append(link);}}
init();
