/* REGION: LEOLA.READER | TAG: PAGEFLIP.PRESERVATION
WHAT: canonical book DOM and exact native PageFlip initializer, top-left Leola.
WHO: LeeWay; WHY: legacy flip callback recursively called turnToPage and froze the browser.
WHERE: adapter view only; WHEN: 2026-09-16; HOW: preserve renderer/configuration, replace failed legacy controls.
LICENSE: MIT. Canonical book bytes unchanged. Narration is exact text, not model-generated. */
import {leola} from './leola-presence.js';import {loadState,saveBook} from './learning-state.js';
const books={story:{id:'needle-and-yarn',file:'d6jq33mv39.html',title:'Needle & Yarn'},instruction:{id:'crochet-mastery',file:'0lbzci75tc.html',title:'Crochet Mastery'}};
const params=new URLSearchParams(location.search),book=books[params.get('book')]||books.instruction;const frame=document.querySelector('#book-frame'),status=document.querySelector('#reader-status');let flip=null,auto=false,readId=0;
document.title=book.title+' · Read with Leola';leola.show('reader');
const controls=document.createElement('div');controls.className='leola-reader-controls';controls.innerHTML='<span class="leola-page-label">Preparing book…</span><button data-read="prev">← Previous</button><button data-read="next">Next →</button><button data-read="page">Read this page</button><button data-read="all">Read onward</button><button data-read="stop">Stop reading</button><button data-read="slow">Slower voice</button>';leola.el.append(controls);
function halt(){auto=false;readId++;leola.stop();}
function content(index){const p=frame.contentDocument?.querySelectorAll('.page')[index];if(!p)return '';const main=p.querySelector('.story-page,.instruction-page,.cover-page,.dedication-page')||p;return main.textContent.replace(/\s+/g,' ').trim()||p.querySelector('img')?.alt||'';}
async function read(all=false){if(!flip)return;halt();auto=all;const id=readId;let index=flip.getCurrentPageIndex();leola.setMuted(false);do{const text=content(index);status.textContent=`Reading page ${index+1} of ${flip.getPageCount()}.`;const ok=await leola.speak(text||'This page is an illustration.');if(!ok||id!==readId||!auto)break;index++;if(index>=flip.getPageCount()){auto=false;break;}flip.flip(index);await new Promise(r=>setTimeout(r,1100));}while(auto&&id===readId);}
controls.addEventListener('click',e=>{const key=e.target.closest('[data-read]')?.dataset.read;if(!key||!flip)return;if(key==='page')read(false);if(key==='all')read(true);if(key==='stop')halt();if(key==='slow'){leola.rate=.8;status.textContent='Narration speed: slower';}if(key==='next'||key==='prev'){halt();key==='next'?flip.flipNext():flip.flipPrev();}});
leola.el.querySelector('[data-action=stop]').addEventListener('click',halt);document.querySelector('.reader-exit').addEventListener('click',halt);
function update(){const index=flip.getCurrentPageIndex();controls.querySelector('.leola-page-label').textContent=`${book.title} · ${index+1} / ${flip.getPageCount()}`;const ok=saveBook(book.id,index,flip.getPageCount());status.textContent=ok?'Position saved on this device.':'Position could not be saved: browser storage unavailable.';window.__readerProof={book:book.id,page:index,count:flip.getPageCount(),engine:'original-page-flip',canonicalFileUnchanged:true,originalInitializerPreserved:true};}
async function init(){try{
const response=await fetch(book.file);if(!response.ok)throw new Error('Book returned '+response.status);const original=await response.text();
const initializer=original.match(/const pageFlip = new St\.PageFlip\(document\.getElementById\('book'\),\s*\{[\s\S]*?\}\);/);
if(!initializer)throw new Error('Canonical PageFlip initializer changed; manual reconciliation required');
const doc=new DOMParser().parseFromString(original,'text/html');const base=doc.createElement('base');base.href=new URL('./',location.href).href;doc.head.prepend(base);
let engineCount=0;for(const script of [...doc.querySelectorAll('script')]){const src=script.getAttribute('src')||'';if(src.includes('page-flip')&&src.includes('cdn.jsdelivr.net/'))engineCount++;else script.remove();}if(engineCount!==1)throw new Error('Expected exactly one canonical PageFlip engine');
const style=doc.createElement('style');style.textContent='#agent-lee-card,.agent-lee-card,.home-button,#speak-btn,#stop-btn,.voice-controls,#debug-overlay{display:none!important}';doc.head.append(style);
const script=doc.createElement('script');script.textContent=`window.addEventListener('load',function(){const isMobile=window.innerWidth<768;const viewportWidth=window.innerWidth;const viewportHeight=window.innerHeight;${initializer[0]} pageFlip.loadFromHTML(document.querySelectorAll('.page'));window.pageFlip=pageFlip;const loader=document.getElementById('loader');if(loader)loader.style.display='none';document.addEventListener('keydown',function(e){if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();pageFlip.flipNext();}else if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();pageFlip.flipPrev();}});});`;doc.body.append(script);
frame.addEventListener('load',()=>{try{flip=frame.contentWindow.pageFlip;if(!flip)throw new Error('Original PageFlip did not initialize');flip.on('flip',update);frame.contentDocument.addEventListener('pointerdown',halt,{capture:true});frame.contentDocument.addEventListener('keydown',halt,{capture:true});const saved=loadState().books[book.id];const target=params.has('page')?Number(params.get('page')):saved?.page;if(Number.isInteger(target)&&target>=0&&target<flip.getPageCount())flip.turnToPage(target);update();}catch(e){status.textContent='Reader could not start: '+e.message;}});
frame.srcdoc='<!doctype html>'+doc.documentElement.outerHTML;
}catch(e){status.textContent='Book unavailable: '+e.message;const link=document.createElement('a');link.href=book.file;link.textContent='Open the original book directly';link.className='reader-exit';link.style.top='60px';document.body.append(link);}}
init();
