/* REGION: LEOLA.WORLD | TAG: ROLLBACK.3D.ENTRANCE.V1
WHAT: restored Three.js approach, sliding glass doors and walk-through.
WHO: Creator-approved rollback. WHY: recover the accepted pre-regression entry experience.
HOW: bounded procedural scene; desk experience begins after entered event. LICENSE: MIT. */
import * as T from 'three';
const ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
export class LibraryWorld extends EventTarget{
 constructor(host){super();this.host=host;this.scene=new T.Scene();this.scene.background=new T.Color('#cad0c2');this.scene.fog=new T.Fog('#bac4b1',38,92);this.camera=new T.PerspectiveCamera(48,1,.1,130);this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;host.append(this.renderer.domElement);this.phase='outside';this.start=performance.now();this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.disposed=false;this.build();this.camera.position.set(1.5,3.3,26);this.camera.lookAt(0,3,4);this.resize=()=>{const w=Math.max(1,innerWidth),h=Math.max(1,innerHeight);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h)};this.resize();addEventListener('resize',this.resize);this.tick=this.tick.bind(this);this.raf=requestAnimationFrame(this.tick)}
 material(color,roughness=.82){return new T.MeshStandardMaterial({color,roughness})}
 box(name,x,y,z,w,h,d,color,parent=this.scene){const m=new T.Mesh(new T.BoxGeometry(w,h,d),typeof color==='string'?this.material(color):color);m.name=name;m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 label(text,x,y,z,w,h,font=50,bg='#6b4a31',fg='#fff0cf'){const c=document.createElement('canvas');c.width=1024;c.height=256;const q=c.getContext('2d');q.fillStyle=bg;q.fillRect(0,0,c.width,c.height);q.textAlign='center';q.textBaseline='middle';q.fillStyle=fg;q.font=`700 ${font}px Georgia`;q.fillText(text,512,132,930);const tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tx}));m.position.set(x,y,z);this.scene.add(m)}
 planter(x,z){const pot=new T.Mesh(new T.CylinderGeometry(.7,.46,.9,18),this.material('#b77a50'));pot.position.set(x,.5,z);this.scene.add(pot);for(let i=0;i<7;i++){const leaf=new T.Mesh(new T.SphereGeometry(.5,10,8),this.material(i%2?'#47704a':'#69875b'));leaf.scale.set(.5,1.4,.6);leaf.position.set(x+Math.sin(i*2.3)*.38,1.35+(i%3)*.23,z+Math.cos(i*2.3)*.3);leaf.rotation.z=Math.sin(i)*.6;this.scene.add(leaf)}}
 shelf(x,z){const g=new T.Group();g.position.set(x,0,z);this.scene.add(g);this.box('shelf-back',0,2.35,0,5,4.7,.25,'#63503b',g);for(let y=.28;y<=4.7;y+=1.1){this.box('shelf',0,y,.42,5.2,.12,1.1,'#a6784d',g);for(let i=0;i<9;i++){const colors=['#875a47','#b59c6b','#557667','#ddd0a7','#725d68'];this.box('book',-2.15+i*.51,y+.49,.45,.34,.84-(i%3)*.06,.7,colors[(i+Math.round(y))%colors.length],g)}}}
 build(){this.scene.add(new T.HemisphereLight('#fff9e6','#526d58',2.1));const sun=new T.DirectionalLight('#fff0cb',2.8);sun.position.set(-9,15,14);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-22,right:22,top:22,bottom:-22,near:1,far:65});this.scene.add(sun);const fill=new T.PointLight('#ffdea8',120,36,2);fill.position.set(0,6,-6);this.scene.add(fill);
 this.box('forecourt',0,-.2,15,65,.3,60,'#8fa06f');this.box('path',0,.01,20,8,.04,38,'#c9b18d');this.box('library-floor',0,.015,-10,32,.2,40,'#a4845b');this.box('left-wall',-16,4,-9,.5,8,38,'#ded3b6');this.box('right-wall',16,4,-9,.5,8,38,'#ded3b6');this.box('rear-wall',0,4,-28,32,8,.6,'#6e8263');this.box('ceiling',0,8.3,-9,33,.5,39,'#ece2c8');this.box('front-left',-10.5,3.8,7,11,7.6,.7,'#d9d4bc');this.box('front-right',10.5,3.8,7,11,7.6,.7,'#d9d4bc');this.box('lintel',0,6.65,7,11,1.9,.9,'#6c4a31');this.label("LEOLA'S LEARNING LIBRARY",0,6.6,7.48,10.1,1.23,48);this.label('A LITTLE WONDER · A PLACE TO BELONG',0,7.8,7.5,8,.38,34,'#d9c49c','#5b3b26');this.box('welcome-mat',0,.14,8.6,7,.03,2,'#3c5440');
 this.doors=[];const glass=new T.MeshPhysicalMaterial({color:'#a4cdc9',transparent:true,opacity:.27,roughness:.12,metalness:.08,depthWrite:false,side:T.DoubleSide});for(const side of [-1,1]){const group=new T.Group();group.position.set(side*2.48,0,7.24);this.scene.add(group);this.box('glass',0,2.82,0,4.93,5.6,.055,glass,group);for(const x of [-2.42,2.42])this.box('glass-frame',x,2.8,.045,.09,5.62,.095,'#4d4337',group);for(const y of [.08,5.57])this.box('glass-frame',0,y,.045,4.9,.08,.095,'#4d4337',group);this.box('door-handle',-side*1.98,2.77,.18,.07,.7,.08,'#c3ad78',group);this.doors.push(group)}
 this.planter(-7.5,9);this.planter(7.5,9);for(const x of [-12,12])for(const z of [-2,-12,-22])this.shelf(x,z);for(const z of [-5,-15]){this.box('reading-table',0,1.2,z,5,.2,2.4,'#9c7650');for(const x of [-1.9,1.9]){this.box('chair-seat',x,.65,z+1.7,.9,.13,.9,'#597b67');this.box('chair-back',x,1.25,z+2.08,.9,1.2,.12,'#597b67')}}}
 enter(reduced=false){if(this.phase!=='outside')return;this.reduced=reduced;this.phase='entering';this.enteredAt=performance.now();this.dispatchEvent(new Event('walkstart'))}
 finish(){if(this.phase==='inside')return;this.phase='inside';this.doors[0].position.x=-7.65;this.doors[1].position.x=7.65;this.camera.position.set(0,2.8,1.5);this.camera.lookAt(0,2.2,-14);this.dispatchEvent(new Event('entered'))}
 tick(t){if(this.disposed)return;this.raf=requestAnimationFrame(this.tick);if(document.hidden)return;if(this.phase==='outside'){const f=this.reduced?1:ease(Math.min((t-this.start)/4000,1));this.camera.position.set(1.5*(1-f),3.3-.3*f,26-4*f);this.camera.lookAt(0,3.1,4)}if(this.phase==='entering'){const elapsed=(t-this.enteredAt)/1000;if(this.reduced)this.finish();else{const approach=ease(Math.min(elapsed/3,1)),door=ease(T.MathUtils.clamp((elapsed-2.1)/3,0,1)),inside=ease(T.MathUtils.clamp((elapsed-4.3)/5.2,0,1));this.camera.position.set(0,3-.2*inside,22-11*approach-9.5*inside);this.camera.lookAt(0,3.1-.9*inside,4-18*inside);this.doors[0].position.x=-2.48-5.17*door;this.doors[1].position.x=2.48+5.17*door;if(elapsed>=9.5)this.finish()}}this.renderer.render(this.scene,this.camera)}
 dispose(){this.disposed=true;cancelAnimationFrame(this.raf);removeEventListener('resize',this.resize);this.scene.traverse(o=>{o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose()});this.renderer.dispose();this.renderer.domElement.remove()}
}