/* REGION: LEOLA.ENTRY | TAG: ROLLBACK.JOURNEY.V1
WHAT: restored 3D entrance lifecycle and handoff to the recovered desk experience.
WHO: Creator-approved rollback. WHY: restore the last accepted visitor journey. LICENSE: MIT. */
import {safeSetting} from './learning-state.js';
const $=s=>document.querySelector(s);let world=null,entering=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,sound=true,stepTimer=null;
function caption(text){const n=$('#caption');n.textContent=text;n.hidden=!text}
function setSound(value){sound=!!value;safeSetting('sound',sound);const b=$('#sound-toggle');b.textContent=sound?'Sound on':'Sound off';b.setAttribute('aria-pressed',String(!sound))}
function speak(text){if(!sound||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.94;speechSynthesis.speak(u)}
function footsteps(){clearInterval(stepTimer);let n=0;stepTimer=setInterval(()=>{n++;if(n>=13)clearInterval(stepTimer)},reduced?10:420)}
function enter(useVoice){if(entering)return;entering=true;$('#entry').hidden=true;$('#arrival').hidden=false;document.body.classList.add('touring');setSound(useVoice);caption('The glass doors are opening. Walk inside and meet Leola at her desk.');if(useVoice){if(navigator.mediaDevices?.getUserMedia&&window.isSecureContext)navigator.mediaDevices.getUserMedia({audio:true,video:false}).then(s=>s.getTracks().forEach(t=>t.stop())).catch(()=>{});speak('Welcome. The doors are opening. Come inside and meet me at the desk.')}footsteps();world?.enter(reduced)}
function goDesk(){clearInterval(stepTimer);speechSynthesis?.cancel?.();document.body.classList.add('entered');caption('You are inside. Walking to Leola’s desk…');setTimeout(()=>location.href='library-desk.html',reduced?20:380)}
$('#open-doors').addEventListener('click',()=>enter(true));$('#quiet-entry').addEventListener('click',()=>enter(false));$('#skip-tour').addEventListener('click',()=>location.href='library-desk.html');$('#skip-resources').addEventListener('click',e=>{e.preventDefault();location.href='library-desk.html'});
$('#motion-toggle').setAttribute('aria-pressed',String(reduced));$('#motion-toggle').textContent=reduced?'Motion reduced':'Reduce motion';$('#motion-toggle').addEventListener('click',()=>{reduced=!reduced;$('#motion-toggle').setAttribute('aria-pressed',String(reduced));$('#motion-toggle').textContent=reduced?'Motion reduced':'Reduce motion';if(world)world.reduced=reduced});
setSound(safeSetting('sound')!=='false');$('#sound-toggle').addEventListener('click',()=>setSound(!sound));
async function init(){try{const {LibraryWorld}=await import('./library-world.js');world=new LibraryWorld($('#world'));world.addEventListener('entered',goDesk);$('#load-status').textContent='Your library is ready.';$('#open-doors').disabled=false;$('#quiet-entry').disabled=false;$('#open-doors').textContent='Open the glass doors ↗';window.__leolaRelease={version:'rollback-3d-magic-desk',stage:'ready',renderMode:'WebGL'};}catch(e){console.warn('3D entrance unavailable; desk route retained.',e.message);$('#load-status').textContent='3D rendering is unavailable. You can still enter the library.';$('#open-doors').disabled=false;$('#quiet-entry').disabled=false;$('#open-doors').textContent='Enter the library';$('#open-doors').onclick=()=>location.href='library-desk.html';window.__leolaRelease={version:'rollback-3d-magic-desk',stage:'fallback',renderMode:'accessible-fallback'};}}
init();