/* REGION: LEOLA.ENTRY | TAG: JOURNEY.V4
WHAT: consent, persistent-guide introduction, verified destination routes.
WHO: LeeWay; WHY: approved visitor journey; WHERE: home; WHEN: 2026-09-16;
HOW: explicit states; denied microphone never blocks content. LICENSE: MIT. */
import {leola} from './leola-presence.js';
import {loadState,saveName,storageAvailable,safeSetting} from './learning-state.js';
const $=s=>document.querySelector(s);let world=null,entering=false,inside=false,voice=false,lastFocus=null;let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
export const GREETING="Welcome to Leola's Instructional Library. I'm Leola, your AI library guide and crochet teacher. I'll stay with you throughout your visit, not just here at the door. I can read our storybooks and instructional books with you, explain the crochet lessons, and help you find video training and practice in the Game House. Ask me a question, tell me to repeat, or ask me to slow down. You can always choose voice or text. Let's discover something together.";
leola.caption=$('#caption');leola.hide();
function setSound(value){leola.setMuted(!value);const b=$('#sound-toggle');b.textContent=value?'Sound on':'Sound off';b.setAttribute('aria-pressed',String(!value));b.setAttribute('aria-label',value?'Turn sound off':'Turn sound on');}
setSound(!leola.muted);$('#sound-toggle').addEventListener('click',()=>setSound(leola.muted));
$('#motion-toggle').setAttribute('aria-pressed',String(reduced));$('#motion-toggle').addEventListener('click',()=>{reduced=!reduced;$('#motion-toggle').setAttribute('aria-pressed',String(reduced));$('#motion-toggle').textContent=reduced?'Motion reduced':'Reduce motion';if(world)world.reduced=reduced;});
function showDestinations(){if(inside)return;inside=true;document.body.classList.remove('touring');document.body.classList.add('entered');$('#arrival').hidden=true;$('#destinations').hidden=false;leola.show();$('#destinations').focus({preventScroll:true});if(voice)leola.speak(GREETING);else{leola.setCaption(GREETING);leola.setState('captions','Caption mode · questions welcome');}window.__leolaRelease={version:'4.0.0-entry',stage:'inside',renderMode:world?'WebGL':'accessible-fallback'};}
function enter(useVoice){if(entering)return;entering=true;voice=useVoice;$('#entry').hidden=true;$('#arrival').hidden=false;document.body.classList.add('touring');setSound(useVoice);if(useVoice){leola.requestMicrophone().then(allowed=>safeSetting('microphoneGranted',allowed));leola.speak("Welcome. The doors are opening. Come inside and I'll introduce you to the library.");}else leola.setCaption('Welcome. Come inside. I will guide you with captions, and you can ask questions by typing.');if(world)world.enter(reduced);else showDestinations();}
function skip(){voice=false;entering=true;$('#entry').hidden=true;leola.stop();if(world&&world.phase!=='inside')world.finish();else showDestinations();}
$('#open-doors').addEventListener('click',()=>enter(true));$('#quiet-entry').addEventListener('click',()=>enter(false));$('#skip-tour').addEventListener('click',()=>{if(world&&world.phase!=='inside')world.finish();else showDestinations();});$('#skip-resources').addEventListener('click',e=>{e.preventDefault();skip();});$('#replay-greeting').addEventListener('click',()=>{leola.show();leola.speak(GREETING);});addEventListener('keydown',e=>{if(e.key==='Escape'){leola.stop();if(entering&&!inside){world?world.finish():showDestinations();}}});
const routes={story:'reader.html?book=story',instruction:'reader.html?book=instruction',video:'training.html',games:'game-house.html'};
document.querySelectorAll('[data-destination]').forEach(a=>a.addEventListener('click',()=>leola.stop()));
const dialog=$('#progress-dialog');$('#progress-open').addEventListener('click',()=>{lastFocus=document.activeElement;renderProgress();dialog.showModal();});dialog.addEventListener('close',()=>lastFocus?.focus());$('#save-pass').addEventListener('click',()=>{const result=saveName($('#display-name').value);$('#storage-status').textContent=result.ok?'Device pass saved. This is not a cloud membership account.':'Storage is blocked. Your pass could not be saved.';renderProgress();});
function renderProgress(){const state=loadState();$('#display-name').value=state.displayName;const box=$('#progress-content');box.replaceChildren();const title=document.createElement('p');title.textContent=state.cardId?`${state.displayName||'Visitor'} · ${state.cardId}`:'No device pass yet.';box.append(title);for(const [id,r]of Object.entries(state.books)){if(!r||!Number.isInteger(r.page)||!Number.isInteger(r.count))continue;const p=document.createElement('p');p.className='progress-item';p.textContent=`${id==='crochet-mastery'?'Crochet Mastery':'Needle & Yarn'} — page ${r.page+1} of ${r.count}`;box.append(p);}for(const [id,r]of Object.entries(state.games)){if(!r)continue;const p=document.createElement('p');p.className='progress-item';p.textContent=`${id} — ${Number(r.completed)||0} practice tasks recorded on this device`;box.append(p);}if(!Object.keys(state.books).length&&!Object.keys(state.games).length){const p=document.createElement('p');p.textContent='Open a book or practice a task to begin recording progress.';box.append(p);}if(!storageAvailable())$('#storage-status').textContent='Browser storage is unavailable. No cloud save is being claimed.';}
async function init(){await leola.ready;try{const {LibraryWorld}=await import('./library-world.js');world=new LibraryWorld($('#world'),leola);world.addEventListener('entered',showDestinations);world.addEventListener('destination',e=>{leola.stop();location.href=routes[e.detail];});$('#load-status').textContent='Your library is ready.';}catch(e){console.warn('3D entrance unavailable; accessible navigation retained.',e.message);$('#load-status').textContent='3D rendering is unavailable on this device. You can still enter and read.';}$('#open-doors').disabled=false;$('#quiet-entry').disabled=false;$('#open-doors').textContent='Open doors with voice ↗';window.__leolaRelease={version:'4.0.0-entry',stage:inside?'inside':'ready',renderMode:world?'WebGL':'accessible-fallback'};if(new URLSearchParams(location.search).get('inside')==='1')skip();}
init();
