import {hydrateAssets} from './asset-loader.js';
await hydrateAssets();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='leola.magic.desk.card.v1';let member=loadCard(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,sound=true,currentText="Welcome inside. I'm Leola, your librarian, reader, crochet teacher, and game coach.";let book=null;
function loadCard(){try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return v?.name&&v?.card?v:null}catch{return null}}
function saveCard(v){try{localStorage.setItem(KEY,JSON.stringify(v));return true}catch{return false}}
function talk(text){currentText=text;$('#speech-copy').textContent=text;if(!sound||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.94;speechSynthesis.speak(u)}
function stop(){speechSynthesis?.cancel?.()}
function sparkles(n=30){const host=$('#magic');for(let i=0;i<n;i++){const e=document.createElement('i');e.className='spark';e.style.left=(55+Math.random()*30)+'%';e.style.top=(35+Math.random()*45)+'%';e.style.setProperty('--x',(Math.random()*260-130)+'px');e.style.setProperty('--y',(Math.random()*220-160)+'px');host.append(e);setTimeout(()=>e.remove(),1900)}}
function fillCard(){if(!member)return;$('#card-name').textContent=member.name;$('#card-number').textContent=member.card;$('#card-date').textContent=new Date(member.issuedAt).toLocaleDateString();$('#my-card').hidden=false;$('#member-note').textContent=member.name+' · '+member.card}
function reveal(){member&&fillCard();$('#resources').hidden=false;$('#onboarding').hidden=true;talk(member?`Welcome back, ${member.name}. Your library is ready.`:'Your library is ready.')}
function presentCard(){fillCard();$('#card-save-status').textContent=member.saved?'Guest card saved on this device.':'Temporary guest card; this browser could not save it.';$('#card-dialog').showModal();sparkles(38);talk(`Here you are, ${member.name}. Your Leola's Learning Library card is ready.`)}
function resetVisitor(){if(member&&!confirm('Start a different guest card on this device?'))return;try{localStorage.removeItem(KEY)}catch{}member=null;$('#resources').hidden=true;$('#my-card').hidden=true;$('#returning').hidden=true;$('#card-form').hidden=false;$('#onboarding').hidden=false;$('#member-name').value='';$('#member-email').value='';$('#member-name').focus()}
function offerBook(kind){book=kind;const story=kind==='story';$('#book-heading').textContent=story?'Leola hands you Needle & Yarn.':'Leola hands you Crochet Mastery.';$('#book-offer-copy').textContent=story?'Take the story with you and open it when you are ready.':'Take the guide with you and open it when you are ready.';const src=document.querySelector(`[data-book="${kind}"] .mini-book`).cloneNode(true);$('#offered-book').replaceChildren(src);$('#receive-book').href='reader.html?book='+kind;$('#book-dialog').showModal();sparkles(18);talk(story?'Here is Needle and Yarn. Let us read together.':'Here is Crochet Mastery. Let us learn together.')}
$('#card-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#member-name').value.trim(),email=$('#member-email').value.trim();if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){$('#form-status').textContent='Enter a name and valid email address.';return}member={name,email,card:'LLL-'+crypto.randomUUID().replaceAll('-','').slice(0,10).toUpperCase(),issuedAt:new Date().toISOString(),saved:false};member.saved=saveCard({...member,saved:true});$('#form-status').textContent='';$('#onboarding').hidden=true;presentCard()});
$('#continue-card').addEventListener('click',presentCard);$('#different-visitor').addEventListener('click',resetVisitor);$('#my-card').addEventListener('click',presentCard);$('#close-card').addEventListener('click',()=>$('#card-dialog').close());$('#keep-card').addEventListener('click',()=>{$('#card-dialog').close();reveal()});
let flipped=false;$('#flip-card').addEventListener('click',()=>{flipped=!flipped;$('#personal-card').style.transform=`rotateX(5deg) rotateY(${flipped?175:-5}deg)`});
$$('[data-book]').forEach(b=>b.addEventListener('click',()=>offerBook(b.dataset.book)));$('#close-book').addEventListener('click',()=>$('#book-dialog').close());$$('#resources a,#receive-book').forEach(a=>a.addEventListener('click',stop));
$('#sound-toggle').addEventListener('click',()=>{sound=!sound;$('#sound-toggle').textContent=sound?'Sound on':'Sound off';$('#sound-toggle').setAttribute('aria-pressed',String(!sound));if(!sound)stop()});$('#motion-toggle').addEventListener('click',()=>{reduced=!reduced;$('#motion-toggle').textContent=reduced?'Motion reduced':'Gentle motion';$('#motion-toggle').setAttribute('aria-pressed',String(reduced))});$('#replay').addEventListener('click',()=>talk(currentText));$('#stop').addEventListener('click',stop);
$('#desk-art').addEventListener('error',()=>{$('#form-status').textContent='The desk artwork did not load. The card and resource links still work.'});
if(member){fillCard();$('#card-form').hidden=true;$('#returning').hidden=false;$('#returning-copy').textContent=`Welcome back, ${member.name}. Your card is here.`;$('#onboarding').hidden=false}else{$('#onboarding').hidden=false}
talk(currentText);window.__leolaDesk={get member(){return member?{name:member.name,card:member.card,saved:member.saved}:null},get book(){return book},resources:()=>!$('#resources').hidden,assetErrors:()=>$$('[data-asset-error]').map(n=>n.dataset.assetError)};
