/* REGION: SISTA.LEE.BRAIN | TAG: BROWSER.SMALL.MODEL.V1
WHAT: instant curriculum-grounded answers plus optional on-device 360M model.
WHO: Sista Lee / Leola's Learning Library.
HOW: tiny JSON retrieval answers immediately; WebGPU model warms asynchronously.
LICENSE: MIT adapter. Model: HuggingFaceTB/SmolLM2-360M-Instruct (Apache-2.0). */
const MODEL_ID='HuggingFaceTB/SmolLM2-360M-Instruct';
const TRANSFORMERS='https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.3.0';
export class SistaBrain extends EventTarget{
 constructor(){super();this.status='instant-reference';this.knowledge=null;this.generator=null;this.loading=null;this.knowledgePromise=this.loadKnowledge();this.scheduleWarm();}
 setStatus(status,detail=''){this.status=status;this.dispatchEvent(new CustomEvent('status',{detail:{status,detail}}));}
 async loadKnowledge(){if(this.knowledge)return this.knowledge;try{const r=await fetch(new URL('../content/leola-crochet-knowledge.json',import.meta.url));if(!r.ok)throw Error('reference '+r.status);const data=await r.json();this.knowledge=Array.isArray(data.topics)?data.topics:[];}catch{this.knowledge=[];}return this.knowledge;}
 scheduleWarm(){const start=()=>this.warm().catch(()=>{});if('requestIdleCallback'in window)requestIdleCallback(start,{timeout:8000});else setTimeout(start,3500);}
 async warm(){if(this.generator||this.loading)return this.loading;if(!navigator.gpu){this.setStatus('instant-reference','WebGPU unavailable; curated knowledge remains ready.');return null;}this.setStatus('model-loading','Sista Brain is warming in this browser.');this.loading=(async()=>{const {pipeline}=await import(TRANSFORMERS);this.generator=await pipeline('text-generation',MODEL_ID,{device:'webgpu',dtype:'q4f16',progress_callback:p=>{if(p?.status==='progress'&&Number.isFinite(p.progress))this.setStatus('model-loading',`Sista Brain ${Math.round(p.progress)}%`);}});this.setStatus('model-ready','360M on-device model ready.');return this.generator;})().catch(e=>{this.loading=null;this.setStatus('instant-reference','Small model unavailable; curated knowledge remains ready.');return null;});return this.loading;}
 async reference(question){const topics=await this.knowledgePromise;const q=' '+String(question||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ')+' ';const ranked=topics.map(t=>({t,score:(t.keywords||[]).reduce((n,k)=>n+(q.includes(' '+String(k).toLowerCase()+' ')?String(k).length:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);if(!ranked.length)return {text:"I don't have an approved library reference for that yet. Ask me about hooks, yarn, chains, stitches, patterns, colorwork, amigurumi, or finishing.",context:''};const context=ranked.slice(0,2).map(x=>x.t.text).join('\n');return {text:ranked[0].t.text,context};}
 async answer(question){const ref=await this.reference(question);if(!this.generator){this.warm().catch(()=>{});return {text:ref.text,mode:'instant-reference'};}try{const messages=[{role:'system',content:'You are Sista Lee, the warm crochet teacher inside Leola\'s Learning Library. Answer only from the APPROVED REFERENCE below. Never invent crochet instructions. If the reference is insufficient, say you do not know from the library material yet. Keep the answer under 90 words. APPROVED REFERENCE:\n'+(ref.context||ref.text)},{role:'user',content:String(question).slice(0,500)}];const out=await this.generator(messages,{max_new_tokens:96,do_sample:false});const generated=out?.[0]?.generated_text;const text=Array.isArray(generated)?generated.at(-1)?.content:typeof generated==='string'?generated:null;return {text:(text||ref.text).trim(),mode:'smollm2-360m'};}catch{return {text:ref.text,mode:'instant-reference'};}}
}
export const sistaBrain=window.__sistaBrain||(window.__sistaBrain=new SistaBrain());
