/* REGION: LEOLA.VERIFICATION | TAG: BROWSER.ACCEPTANCE
WHAT: bounded browser proof with screenshots, no payment submission or real recording.
WHO: LeeWay; WHY: generated source is not verification; WHERE: GitHub Actions/local.
WHEN: 2026-09-16; HOW: Chromium, fake microphone, explicitly simulated speech callbacks.
LICENSE: MIT. Audible speech quality and model inference are NOT covered by this test. */
const {chromium}=require('playwright');const fs=require('node:fs');const path=require('node:path');const http=require('node:http');const assert=require('node:assert/strict');const crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-evidence');fs.mkdirSync(out,{recursive:true});const checks=[],errors=[];let browser,server;
function check(name,value){checks.push({name,pass:Boolean(value)});assert.ok(value,name);}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.json':'application/json','.glb':'model/gltf-binary'};
function startServer(){return new Promise(resolve=>{server=http.createServer((req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const file=path.resolve(root,pathname==='/'?'index.html':pathname.slice(1));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end('Not found');return;}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res);}catch{res.writeHead(500);res.end('Read failed');}}).listen(0,'127.0.0.1',()=>resolve('http://127.0.0.1:'+server.address().port+'/'));});}
function contractStubs(){window.__micCalls=0;window.__speech=[];const get=navigator.mediaDevices?.getUserMedia?.bind(navigator.mediaDevices);if(get)navigator.mediaDevices.getUserMedia=opts=>{window.__micCalls++;return get(opts)};let timer=null;Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[],cancel:()=>{clearTimeout(timer)},speak:u=>{window.__speech.push(u.text);u.onstart?.();timer=setTimeout(()=>u.onend?.(),20)},speaking:false,onvoiceschanged:null},configurable:true});}
(async()=>{const local=await startServer();const base=process.env.LEOLA_TEST_URL||local;browser=await chromium.launch({headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const ctx=await browser.newContext({viewport:{width:1440,height:960}});await ctx.addInitScript(contractStubs);const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
await page.goto(base,{waitUntil:'networkidle',timeout:60000});await page.waitForFunction(()=>window.__leolaRelease?.stage==='ready',null,{timeout:30000});check('Correct library identity',(await page.title()).includes("Leola's Instructional Library"));check('No microphone access before entry',await page.evaluate(()=>window.__micCalls===0));check('WebGL canvas rendered',await page.locator('#world canvas').count()===1);await page.screenshot({path:path.join(out,'entrance-desktop.png')});
await page.locator('#quiet-entry').click();await page.waitForFunction(()=>window.__leolaRelease?.stage==='inside',null,{timeout:20000});check('Captions entry needs no microphone',await page.evaluate(()=>window.__micCalls===0));check('Four destinations shown',await page.locator('.destination').count()===4);check('Greeting explains persistent role',(await page.locator('#caption').innerText()).includes('stay with you throughout'));await page.screenshot({path:path.join(out,'inside-desktop.png')});
await page.locator('#progress-open').click();await page.locator('#display-name').fill('Release test');await page.locator('#save-pass').click();check('Device pass is not mislabeled as cloud',(await page.locator('#storage-status').innerText()).includes('not a cloud'));await page.locator('.dialog-close').click();await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__leolaRelease?.stage==='ready');check('Local pass survives reload',await page.evaluate(()=>JSON.parse(localStorage.getItem('leola.learning.v1')).displayName==='Release test'));await page.locator('#open-doors').click();await page.waitForTimeout(250);check('Voice entry requests microphone',await page.evaluate(()=>window.__micCalls===1));await page.locator('#skip-tour').click();await page.waitForFunction(()=>window.__leolaRelease?.stage==='inside');
for(const name of ['story','instruction']){await page.goto(base+'reader.html?book='+name,{waitUntil:'networkidle',timeout:60000});await page.waitForFunction(()=>window.__readerProof?.count>1,null,{timeout:20000});const before=await page.evaluate(()=>window.__readerProof.page);await page.locator('[data-read=next]').click();await page.waitForFunction(n=>window.__readerProof.page>n,before);check(name+' native page turn works',true);const after=await page.evaluate(()=>window.__readerProof.page);check(name+' guide at top left',await page.locator('.leola-widget').evaluate(e=>{const r=e.getBoundingClientRect();return r.left<25&&r.top<25}));await page.screenshot({path:path.join(out,name+'-reader.png')});await page.reload({waitUntil:'networkidle'});await page.waitForFunction(n=>window.__readerProof?.page===n,after,{timeout:20000});check(name+' page position restored',true);await page.locator('[data-read=page]').click();await page.waitForTimeout(250);check(name+' exact-text narration dispatched',await page.evaluate(()=>window.__speech.length>0));}
await ctx.close();const mobile=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await mobile.addInitScript(contractStubs);const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto(base,{waitUntil:'networkidle'});await mp.waitForFunction(()=>window.__leolaRelease?.stage==='ready');await mp.screenshot({path:path.join(out,'entrance-mobile.png')});await mp.locator('#quiet-entry').click();await mp.waitForFunction(()=>window.__leolaRelease?.stage==='inside');check('Reduced-motion entry works',true);check('Mobile has no horizontal overflow',await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await mp.screenshot({path:path.join(out,'inside-mobile.png'),fullPage:true});await mobile.close();
const denied=await browser.newContext({reducedMotion:'reduce'});await denied.addInitScript(contractStubs);await denied.addInitScript(()=>navigator.mediaDevices.getUserMedia=()=>Promise.reject(new DOMException('Denied for test','NotAllowedError')));const dp=await denied.newPage();await dp.goto(base,{waitUntil:'networkidle'});await dp.waitForFunction(()=>window.__leolaRelease?.stage==='ready');await dp.locator('#open-doors').click();await dp.waitForFunction(()=>window.__leolaRelease?.stage==='inside');check('Denied microphone does not block entry',await dp.locator('#destinations').isVisible());await denied.close();
for(const [file,hash]of [['d6jq33mv39.html','923cc42cfee63e1dd33e26602e41d01262434bf9fd7cc9464ec96a6dbfffc37f'],['0lbzci75tc.html','33e75fa693e8b068a18ac25f3f57b365169edad03a7de5e8e58caae86ac40109']])check(file+' canonical bytes unchanged',crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')===hash);
check('No uncaught browser errors',errors.length===0);const report={at:new Date().toISOString(),commit:process.env.GITHUB_SHA||null,base,browser:browser.version(),checks,errors,scope:'Entrance, navigation, reader, local save. Not full-product completion.',speech:'Speech callbacks simulated; no audible-quality claim',microphone:'Synthetic browser-test media; no person recorded',modelInference:'NOT_EXECUTED'};fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
})().catch(e=>{fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({at:new Date().toISOString(),checks,errors,error:e.stack},null,2));console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
