/* REGION: LEOLA.VERIFICATION | TAG: LIVE.COZY.ACCEPTANCE.V1
WHAT: browser proof for cozy onboarding, card, video routes and five-cover Game House.
WHO: LeeWay. HOW: isolated Chromium; fake mic/speech only. LICENSE: MIT.
No payment, audible voice-quality, cloud membership, voice clone, or physical-crochet claim. */
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-evidence');fs.mkdirSync(out,{recursive:true});const checks=[],errors=[];let browser,server;
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.b64':'text/plain; charset=utf-8','.png':'image/png'};
function check(n,v){checks.push({name:n,pass:Boolean(v)});assert.ok(v,n)}
function start(){return new Promise(ok=>{server=http.createServer((req,res)=>{try{const n=decodeURIComponent(new URL(req.url,'http://x').pathname),p=path.resolve(root,n==='/'?'index.html':n.slice(1));if(!p.startsWith(root+path.sep)||!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':mime[path.extname(p)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(p).pipe(res)}catch{res.writeHead(500);res.end('Read failed')}}).listen(0,'127.0.0.1',()=>ok('http://127.0.0.1:'+server.address().port+'/'))})}
function stubs(){window.__mic=0;window.__speech=[];Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia:async()=>{window.__mic++;return {getTracks:()=>[{stop(){}}]}}},configurable:true});Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[],cancel(){},speak(u){window.__speech.push(u.text);u.onstart?.();setTimeout(()=>u.onend?.(),5)}},configurable:true});window.SpeechSynthesisUtterance=class{constructor(t){this.text=t}}}
(async()=>{const base=process.env.LEOLA_TEST_URL||await start();browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const ctx=await browser.newContext({viewport:{width:1440,height:960},reducedMotion:'reduce'});await ctx.addInitScript(stubs);const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base,{waitUntil:'domcontentloaded',timeout:60000});check('Correct library identity',(await p.title()).includes("Leola's Instructional Library"));check('No microphone before consent',await p.evaluate(()=>window.__mic===0));check('Static signup panel initially hidden',await p.locator('#onboarding').isHidden());await p.locator('#enter-text').click();await p.locator('#onboarding').waitFor({state:'visible'});check('Caption entry uses no microphone',await p.evaluate(()=>window.__mic===0));await p.locator('#member-name').fill('Release Tester');await p.locator('#member-email').fill('release@example.com');await p.locator('#join-form button[type=submit]').click();check('Personal card opens',await p.locator('#card-dialog').evaluate(e=>e.open));check('Card contains member name',(await p.locator('#card-name').innerText())==='Release Tester');await p.locator('#accept-card').click();check('Exactly four library panels',await p.locator('#resources > .panel').count()===4);check('Exactly five approved game covers',await p.locator('.cover-row a').count()===5);check('Three actual lesson video elements',await p.locator('.mini-videos video').count()===3);await p.waitForFunction(()=>[...document.querySelectorAll('.cover-row img,.mini-videos video')].every(n=>n.src.startsWith('blob:')),{timeout:60000});await p.screenshot({path:path.join(out,'cozy-library.png'),fullPage:true});
await p.goto(base+'training.html',{waitUntil:'domcontentloaded'});check('Training has 3 players',await p.locator('video[controls]').count()===3);check('Training includes single crochet',(await p.locator('body').innerText()).includes('Your First Single Crochet'));await p.waitForFunction(()=>[...document.querySelectorAll('video')].every(n=>n.src.startsWith('blob:')),{timeout:60000});
await p.goto(base+'game-house.html',{waitUntil:'domcontentloaded',timeout:60000});await p.waitForSelector('#covers .cover',{timeout:60000});check('Game House selector has five covers',await p.locator('#covers .cover').count()===5);await p.locator('[data-room=loop]').click();check('Loop Lab opens from its cover',(await p.locator('#room-title').innerText())==='Loop Lab');await p.waitForSelector('#scene canvas',{timeout:60000});check('Game House has WebGL canvas',await p.locator('#scene canvas').count()===1);await p.locator('#turn').click();await p.locator('#pull').click();check('Game action changes progress',Number((await p.locator('#score').innerText()))>0);await p.screenshot({path:path.join(out,'game-house.png'),fullPage:true});
for(const [file,hash] of [['d6jq33mv39.html','923cc42cfee63e1dd33e26602e41d01262434bf9fd7cc9464ec96a6dbfffc37f'],['0lbzci75tc.html','33e75fa693e8b068a18ac25f3f57b365169edad03a7de5e8e58caae86ac40109']])check(file+' canonical bytes unchanged',crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')===hash);
for(const f of ['index.html','game-house.html','training.html','js/leola-presence.js'])check(f+' has no retired avatar filename',!fs.readFileSync(path.join(root,f),'utf8').includes('g444d1542'));
check('No uncaught browser errors',errors.length===0);const result={at:new Date().toISOString(),base,checks,errors,scope:'Cozy reception, local card, playable preview media, five-cover guided Game House',speech:'simulated callbacks',microphone:'synthetic media',physicalCrochet:'NOT_VERIFIED',voiceClone:'NOT_PRODUCED'};fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result))})().catch(e=>{fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server?.close()});
