/* REGION: LEOLA.RELEASE | TAG: STATIC.BUILD.V2
WHAT: deterministic public output including connector-safe base64 media payloads.
WHO: Creator-authorized LeeWay; WHY: generated source is not deploy proof.
LICENSE: MIT. No API source, credentials, tests, evidence, staging, or dependencies are emitted. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const EXCLUDE=new Set(['api','backend','tests','scripts','docs','test-evidence','node_modules','public','lib','evidence','_staging']);
const EXT=/\.(?:html|css|js|mjs|json|png|jpe?g|webp|gif|svg|ico|glb|gltf|bin|b64|mp4|webm|wav|mp3|ogg|vtt|txt)$/i;
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function build(root){
 root=path.resolve(root);const out=path.join(root,'public'),chosen=[];
 function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name,'en'))){if(item.name.startsWith('.')||item.isSymbolicLink())continue;const full=path.join(dir,item.name),rel=path.relative(root,full).split(path.sep).join('/');if(item.isDirectory()){if(!EXCLUDE.has(item.name))walk(full);}else if(EXT.test(item.name)&&!['package.json','package-lock.json','vercel.json'].includes(item.name))chosen.push(rel);}}
 walk(root);
 for(const file of ['index.html','reader.html','game-house.html','training.html','d6jq33mv39.html','0lbzci75tc.html','assets/base64/leola.webp.b64'])if(!chosen.includes(file))throw Error('Required release input missing: '+file);
 if(fs.existsSync(out)&&!fs.existsSync(path.join(out,'.leola-generated')))throw Error('Refusing to replace an unowned output directory');
 if(fs.existsSync(out))fs.rmSync(out,{recursive:true});fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'.leola-generated'),'Generated by tests/static-build.cjs\n');
 const files=[];for(const file of chosen){const source=path.join(root,file),dest=path.join(out,file);fs.mkdirSync(path.dirname(dest),{recursive:true});const bytes=fs.readFileSync(source);fs.writeFileSync(dest,bytes);files.push({path:file,sha256:hash(bytes)});}
 const manifest={schema:2,files};fs.writeFileSync(path.join(out,'build-manifest.json'),JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(path.join(out,'.nojekyll'),'');
 return {status:'BUILT',output:'public',files:files.length,manifestSHA256:hash(JSON.stringify(manifest)),browserTests:'SEPARATE_REQUIRED_GATE'};
}
module.exports={build};if(require.main===module)console.log(JSON.stringify(build(path.resolve(__dirname,'..'))));
